// generated by gen-mocks; DO NOT EDIT

package mock

import (
	"sourcegraph.com/sourcegraph/go-sourcegraph/sourcegraph"
	"sourcegraph.com/sourcegraph/rwvfs"
)

type BuildDataService struct {
	FileSystem_ func(repo sourcegraph.RepoRevSpec) (rwvfs.FileSystem, error)
}

func (s *BuildDataService) FileSystem(repo sourcegraph.RepoRevSpec) (rwvfs.FileSystem, error) {
	return s.FileSystem_(repo)
}

var _ sourcegraph.BuildDataService = (*BuildDataService)(nil)
