// generated by gen-mocks; DO NOT EDIT

package mock

import "sourcegraph.com/sourcegraph/go-sourcegraph/sourcegraph"

type DefsService struct {
	Get_          func(def sourcegraph.DefSpec, opt *sourcegraph.DefGetOptions) (*sourcegraph.Def, sourcegraph.Response, error)
	List_         func(opt *sourcegraph.DefListOptions) ([]*sourcegraph.Def, sourcegraph.Response, error)
	ListRefs_     func(def sourcegraph.DefSpec, opt *sourcegraph.DefListRefsOptions) ([]*sourcegraph.Ref, sourcegraph.Response, error)
	ListExamples_ func(def sourcegraph.DefSpec, opt *sourcegraph.DefListExamplesOptions) ([]*sourcegraph.Example, sourcegraph.Response, error)
	ListAuthors_  func(def sourcegraph.DefSpec, opt *sourcegraph.DefListAuthorsOptions) ([]*sourcegraph.AugmentedDefAuthor, sourcegraph.Response, error)
	ListClients_  func(def sourcegraph.DefSpec, opt *sourcegraph.DefListClientsOptions) ([]*sourcegraph.AugmentedDefClient, sourcegraph.Response, error)
}

func (s *DefsService) Get(def sourcegraph.DefSpec, opt *sourcegraph.DefGetOptions) (*sourcegraph.Def, sourcegraph.Response, error) {
	return s.Get_(def, opt)
}

func (s *DefsService) List(opt *sourcegraph.DefListOptions) ([]*sourcegraph.Def, sourcegraph.Response, error) {
	return s.List_(opt)
}

func (s *DefsService) ListRefs(def sourcegraph.DefSpec, opt *sourcegraph.DefListRefsOptions) ([]*sourcegraph.Ref, sourcegraph.Response, error) {
	return s.ListRefs_(def, opt)
}

func (s *DefsService) ListExamples(def sourcegraph.DefSpec, opt *sourcegraph.DefListExamplesOptions) ([]*sourcegraph.Example, sourcegraph.Response, error) {
	return s.ListExamples_(def, opt)
}

func (s *DefsService) ListAuthors(def sourcegraph.DefSpec, opt *sourcegraph.DefListAuthorsOptions) ([]*sourcegraph.AugmentedDefAuthor, sourcegraph.Response, error) {
	return s.ListAuthors_(def, opt)
}

func (s *DefsService) ListClients(def sourcegraph.DefSpec, opt *sourcegraph.DefListClientsOptions) ([]*sourcegraph.AugmentedDefClient, sourcegraph.Response, error) {
	return s.ListClients_(def, opt)
}

var _ sourcegraph.DefsService = (*DefsService)(nil)
