// generated by gen-mocks; DO NOT EDIT

package mock

import "sourcegraph.com/sourcegraph/go-sourcegraph/sourcegraph"

type DeltasService struct {
	Get_                 func(ds sourcegraph.DeltaSpec, opt *sourcegraph.DeltaGetOptions) (*sourcegraph.Delta, sourcegraph.Response, error)
	ListUnits_           func(ds sourcegraph.DeltaSpec, opt *sourcegraph.DeltaListUnitsOptions) ([]*sourcegraph.UnitDelta, sourcegraph.Response, error)
	ListDefs_            func(ds sourcegraph.DeltaSpec, opt *sourcegraph.DeltaListDefsOptions) (*sourcegraph.DeltaDefs, sourcegraph.Response, error)
	ListFiles_           func(ds sourcegraph.DeltaSpec, opt *sourcegraph.DeltaListFilesOptions) (*sourcegraph.DeltaFiles, sourcegraph.Response, error)
	ListAffectedAuthors_ func(ds sourcegraph.DeltaSpec, opt *sourcegraph.DeltaListAffectedAuthorsOptions) ([]*sourcegraph.DeltaAffectedPerson, sourcegraph.Response, error)
	ListAffectedClients_ func(ds sourcegraph.DeltaSpec, opt *sourcegraph.DeltaListAffectedClientsOptions) ([]*sourcegraph.DeltaAffectedPerson, sourcegraph.Response, error)
}

func (s *DeltasService) Get(ds sourcegraph.DeltaSpec, opt *sourcegraph.DeltaGetOptions) (*sourcegraph.Delta, sourcegraph.Response, error) {
	return s.Get_(ds, opt)
}

func (s *DeltasService) ListUnits(ds sourcegraph.DeltaSpec, opt *sourcegraph.DeltaListUnitsOptions) ([]*sourcegraph.UnitDelta, sourcegraph.Response, error) {
	return s.ListUnits_(ds, opt)
}

func (s *DeltasService) ListDefs(ds sourcegraph.DeltaSpec, opt *sourcegraph.DeltaListDefsOptions) (*sourcegraph.DeltaDefs, sourcegraph.Response, error) {
	return s.ListDefs_(ds, opt)
}

func (s *DeltasService) ListFiles(ds sourcegraph.DeltaSpec, opt *sourcegraph.DeltaListFilesOptions) (*sourcegraph.DeltaFiles, sourcegraph.Response, error) {
	return s.ListFiles_(ds, opt)
}

func (s *DeltasService) ListAffectedAuthors(ds sourcegraph.DeltaSpec, opt *sourcegraph.DeltaListAffectedAuthorsOptions) ([]*sourcegraph.DeltaAffectedPerson, sourcegraph.Response, error) {
	return s.ListAffectedAuthors_(ds, opt)
}

func (s *DeltasService) ListAffectedClients(ds sourcegraph.DeltaSpec, opt *sourcegraph.DeltaListAffectedClientsOptions) ([]*sourcegraph.DeltaAffectedPerson, sourcegraph.Response, error) {
	return s.ListAffectedClients_(ds, opt)
}

var _ sourcegraph.DeltasService = (*DeltasService)(nil)
