// generated by gen-mocks; DO NOT EDIT

package mock

import "sourcegraph.com/sourcegraph/go-sourcegraph/sourcegraph"

type MarkdownService struct {
	Render_ func(markdown []byte, opt sourcegraph.MarkdownOpt) (*sourcegraph.MarkdownData, sourcegraph.Response, error)
}

func (s *MarkdownService) Render(markdown []byte, opt sourcegraph.MarkdownOpt) (*sourcegraph.MarkdownData, sourcegraph.Response, error) {
	return s.Render_(markdown, opt)
}

var _ sourcegraph.MarkdownService = (*MarkdownService)(nil)
