// generated by gen-mocks; DO NOT EDIT

package mock

import "sourcegraph.com/sourcegraph/go-sourcegraph/sourcegraph"

type PeopleService struct {
	Get_ func(person sourcegraph.PersonSpec) (*sourcegraph.Person, sourcegraph.Response, error)
}

func (s *PeopleService) Get(person sourcegraph.PersonSpec) (*sourcegraph.Person, sourcegraph.Response, error) {
	return s.Get_(person)
}

var _ sourcegraph.PeopleService = (*PeopleService)(nil)
