// generated by gen-mocks; DO NOT EDIT

package mock

import (
	"sourcegraph.com/sourcegraph/go-sourcegraph/sourcegraph"
	"sourcegraph.com/sourcegraph/go-vcs/vcs"
)

type RepoTreeService struct {
	Get_    func(entry sourcegraph.TreeEntrySpec, opt *sourcegraph.RepoTreeGetOptions) (*sourcegraph.TreeEntry, sourcegraph.Response, error)
	Search_ func(rev sourcegraph.RepoRevSpec, opt *sourcegraph.RepoTreeSearchOptions) ([]*vcs.SearchResult, sourcegraph.Response, error)
}

func (s *RepoTreeService) Get(entry sourcegraph.TreeEntrySpec, opt *sourcegraph.RepoTreeGetOptions) (*sourcegraph.TreeEntry, sourcegraph.Response, error) {
	return s.Get_(entry, opt)
}

func (s *RepoTreeService) Search(rev sourcegraph.RepoRevSpec, opt *sourcegraph.RepoTreeSearchOptions) ([]*vcs.SearchResult, sourcegraph.Response, error) {
	return s.Search_(rev, opt)
}

var _ sourcegraph.RepoTreeService = (*RepoTreeService)(nil)
