// generated by gen-mocks; DO NOT EDIT

package mock

import "sourcegraph.com/sourcegraph/go-sourcegraph/sourcegraph"

type RepoSettingsService struct {
	GetSettings_    func(repo sourcegraph.RepoSpec) (*sourcegraph.RepoSettings, error)
	UpdateSettings_ func(repo sourcegraph.RepoSpec, settings sourcegraph.RepoSettings) error
}

func (s *RepoSettingsService) GetSettings(repo sourcegraph.RepoSpec) (*sourcegraph.RepoSettings, error) {
	return s.GetSettings_(repo)
}

func (s *RepoSettingsService) UpdateSettings(repo sourcegraph.RepoSpec, settings sourcegraph.RepoSettings) error {
	return s.UpdateSettings_(repo, settings)
}

var _ sourcegraph.RepoSettingsService = (*RepoSettingsService)(nil)
