// generated by gen-mocks; DO NOT EDIT

package mock

import "sourcegraph.com/sourcegraph/go-sourcegraph/sourcegraph"

type RepoGoodiesService struct {
	ListBadges_   func(repo sourcegraph.RepoSpec) ([]*sourcegraph.Badge, error)
	ListCounters_ func(repo sourcegraph.RepoSpec) ([]*sourcegraph.Counter, error)
}

func (s *RepoGoodiesService) ListBadges(repo sourcegraph.RepoSpec) ([]*sourcegraph.Badge, error) {
	return s.ListBadges_(repo)
}

func (s *RepoGoodiesService) ListCounters(repo sourcegraph.RepoSpec) ([]*sourcegraph.Counter, error) {
	return s.ListCounters_(repo)
}

var _ sourcegraph.RepoGoodiesService = (*RepoGoodiesService)(nil)
