// generated by gen-mocks; DO NOT EDIT

package mock

import (
	"sourcegraph.com/sourcegraph/go-sourcegraph/sourcegraph"
	"sourcegraph.com/sourcegraph/srclib/unit"
)

type UnitsService struct {
	Get_  func(spec sourcegraph.UnitSpec) (*unit.RepoSourceUnit, sourcegraph.Response, error)
	List_ func(opt *sourcegraph.UnitListOptions) ([]*unit.RepoSourceUnit, sourcegraph.Response, error)
}

func (s *UnitsService) Get(spec sourcegraph.UnitSpec) (*unit.RepoSourceUnit, sourcegraph.Response, error) {
	return s.Get_(spec)
}

func (s *UnitsService) List(opt *sourcegraph.UnitListOptions) ([]*unit.RepoSourceUnit, sourcegraph.Response, error) {
	return s.List_(opt)
}

var _ sourcegraph.UnitsService = (*UnitsService)(nil)
