// generated by gen-mocks; DO NOT EDIT

package mock

import "sourcegraph.com/sourcegraph/go-sourcegraph/sourcegraph"

type UsersService struct {
	Get_            func(user sourcegraph.UserSpec, opt *sourcegraph.UserGetOptions) (*sourcegraph.User, sourcegraph.Response, error)
	GetSettings_    func(user sourcegraph.UserSpec) (*sourcegraph.UserSettings, sourcegraph.Response, error)
	UpdateSettings_ func(user sourcegraph.UserSpec, settings sourcegraph.UserSettings) (sourcegraph.Response, error)
	ListEmails_     func(user sourcegraph.UserSpec) ([]*sourcegraph.EmailAddr, sourcegraph.Response, error)
	RefreshProfile_ func(userSpec sourcegraph.UserSpec) (sourcegraph.Response, error)
	List_           func(opt *sourcegraph.UsersListOptions) ([]*sourcegraph.User, sourcegraph.Response, error)
	ListOrgs_       func(member sourcegraph.UserSpec, opt *sourcegraph.UsersListOrgsOptions) ([]*sourcegraph.Org, sourcegraph.Response, error)
}

func (s *UsersService) Get(user sourcegraph.UserSpec, opt *sourcegraph.UserGetOptions) (*sourcegraph.User, sourcegraph.Response, error) {
	return s.Get_(user, opt)
}

func (s *UsersService) GetSettings(user sourcegraph.UserSpec) (*sourcegraph.UserSettings, sourcegraph.Response, error) {
	return s.GetSettings_(user)
}

func (s *UsersService) UpdateSettings(user sourcegraph.UserSpec, settings sourcegraph.UserSettings) (sourcegraph.Response, error) {
	return s.UpdateSettings_(user, settings)
}

func (s *UsersService) ListEmails(user sourcegraph.UserSpec) ([]*sourcegraph.EmailAddr, sourcegraph.Response, error) {
	return s.ListEmails_(user)
}

func (s *UsersService) RefreshProfile(userSpec sourcegraph.UserSpec) (sourcegraph.Response, error) {
	return s.RefreshProfile_(userSpec)
}

func (s *UsersService) List(opt *sourcegraph.UsersListOptions) ([]*sourcegraph.User, sourcegraph.Response, error) {
	return s.List_(opt)
}

func (s *UsersService) ListOrgs(member sourcegraph.UserSpec, opt *sourcegraph.UsersListOrgsOptions) ([]*sourcegraph.Org, sourcegraph.Response, error) {
	return s.ListOrgs_(member, opt)
}

var _ sourcegraph.UsersService = (*UsersService)(nil)
